import time

print('Access Matheus')
senha1= 'da'.lower().upper()
autenticacao1 = 1
senha = str(input('Digite sua senha: ')).strip().lower().upper()
if senha == senha1:
	print(' ')

else:
	while senha != senha1:
		senha = str(input('Senha errada, tente novamente: ')).strip().lower().upper()
		print(' ')

autenticacao = int(input('Digite a autenticação: '))
if autenticacao == autenticacao1:
	print(' ')
	print('Bem vindo, Matheus')

else:
	while autenticacao != autenticacao1:
		senha = str(input('Autenticação errada, tente novamente: '))
		print(' ')
	print('Bem vindo, Matheus')

print(' ')
print('------------------')
print('[1] Login')
print('[2] Locate')
print('------------------')
print(' ')
opcao = int(input('Digite o número da opção que deseja: '))


if opcao == 1:
	print(' ')
	print('dados da rede...')
	print(' ')
	print('mensagem sobre segurança...')
	print(' ')
	criptografar = str(input('Deseja criptografar a conexão do programa?  '))

	if criptografar == 'sim'.upper().lower():
			print("Mesagens de criptografia...")
			# voltar para o menu

	if criptografar =='não'.upper().lower():
			print("Não foi possível fazer o login")
			#voltar para o menu

	if criptografar == 'nao'.upper().lower():
		print("Não foi possível fazer o login")
		# voltar para o menu

	else:
			while criptografar != 'sim' and criptografar !='não' and criptografar !='nao':
				criptografar = str(input('Opção inválida, por favor digite sim ou não: '))


				if criptografar == 'sim'.upper().lower():
					print("Mesagens de criptografia...")
				# voltar para o menu

				if criptografar == 'não'.upper().lower():
					print("Não foi possível fazer o login")
				# voltar para o menu

				if criptografar == 'nao'.upper().lower():
					print("Não foi possível fazer o login")
			# voltar para o menu

if opcao == 2:
	print('''	Carteiras dísponíveis:
	Carteira R1
	Carteira R2
	Carteira R3
	Carteira R4
	Carteira R5
	Carteira R6''')
	print(' ')
	opcao1 = str(input('Deseja acessar as carteiras? '))
	if opcao1 == 'sim'.upper().lower():


		ncarteira = int(input('Digite o 'R' + o número da carteira que deseja: '))
		print('')

		saldo1 = float(1.066)
		saldo2 = float(2.87)
		saldo3 = float(0.3)
		saldo4 = float(40.33)
		saldo5 = float(6.78)
		saldo6 = float(1.85)

		if ncarteira == 'R1':
					print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo1))
					transfer= str(input('Deseja transferir o saldo? '))
					if transfer == 'sim'.upper().lower():
						valor = int(input('Qual valor deseja tranferir? '))
						destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
						taxa =  int(0.000041)
						confirmar = str(input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
						if confirmar == 'confirmar'.upper().lower():
							if destino ==1 :
								saldo1=saldo1+valor-taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
								if destino == 2:
									saldo2=saldo2+valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
								if destino == 3:
									saldo3 = saldo3 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
								if destino == 4:
										saldo4 = saldo4 + valor-taxa
										print('Transação 10% conlcuída')
										time.sleep(18)
										print('Transação 20% conlcuída')
										time.sleep(18)
										print('Transação 30% conlcuída')
										time.sleep(18)
										print('Transação 40% conlcuída')
										time.sleep(18)
										print('Transação 50% conlcuída')
										time.sleep(18)
										print('Transação 60% conlcuída')
										time.sleep(18)
										print('Transação 70% conlcuída')
										time.sleep(18)
										print('Transação 80% conlcuída')
										time.sleep(18)
										print('Transação 90% conlcuída')
										time.sleep(18)
										print('Transação 99% conlcuída')
										time.sleep(18)
										print('Transação completamente conlcuída')
										print('O saldo da carteira R4 é {}'.format(saldo4))
								if destino == 5:
									saldo5 = saldo5 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
								if destino == 6:
									saldo6 = saldo6 + valor-taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
								else:
									while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
										destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
										if destino == 1:
											saldo1 = saldo1 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R1 é {}'.format(saldo1))
										if destino == 2:
											saldo2 = saldo2 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R2 é {}'.format(saldo2))
										if destino == 3:
											saldo3 = saldo3 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R3 é {}'.format(saldo3))
										if destino == 4:
											saldo4 = saldo4 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R4 é {}'.format(saldo4))
										if destino == 5:
											saldo5 = saldo5 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R5 é {}'.format(saldo5))
										if destino == 6:
											saldo6 = saldo6 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')

		elif ncarteira == 2:

			print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo2))
			transfer = str(input('Deseja transferir o saldo? '))
			if transfer == 'sim'.upper().lower():
				valor = int(input('Qual valor deseja tranferir? '))
				destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
				taxa = int(0.000041)
				confirmar = str(
				input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
				if confirmar == 'confirmar'.upper().lower():
					if destino == 1:
						saldo1 = saldo1 + valor - taxa
						print('Transação 10% conlcuída')
						time.sleep(18)
						print('Transação 20% conlcuída')
						time.sleep(18)
						print('Transação 30% conlcuída')
						time.sleep(18)
						print('Transação 40% conlcuída')
						time.sleep(18)
						print('Transação 50% conlcuída')
						time.sleep(18)
						print('Transação 60% conlcuída')
						time.sleep(18)
						print('Transação 70% conlcuída')
						time.sleep(18)
						print('Transação 80% conlcuída')
						time.sleep(18)
						print('Transação 90% conlcuída')
						time.sleep(18)
						print('Transação 99% conlcuída')
						time.sleep(18)
						print('Transação completamente conlcuída')
						print('O saldo da carteira R1 é {}'.format(saldo1))
					if destino == 2:
									saldo2 = saldo2 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
					if destino == 3:
									saldo3 = saldo3 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
					if destino == 4:
									saldo4 = saldo4 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R4 é {}'.format(saldo4))
					if destino == 5:
									saldo5 = saldo5 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
					if destino == 6:
									saldo6 = saldo6 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
					else:
						while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
							destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
							if destino == 1:
								saldo1 = saldo1 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R1 é {}'.format(saldo1))
							if destino == 2:
								saldo2 = saldo2 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R2 é {}'.format(saldo2))
							if destino == 3:
								saldo3 = saldo3 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R3 é {}'.format(saldo3))
							if destino == 4:
								saldo4 = saldo4 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R4 é {}'.format(saldo4))
							if destino == 5:
								saldo5 = saldo5 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R5 é {}'.format(saldo5))
							if destino == 6:
								saldo6 = saldo6 + valor - taxa
								print('Transação 10% conlcuída')
								time.sleep(18)
								print('Transação 20% conlcuída')
								time.sleep(18)
								print('Transação 30% conlcuída')
								time.sleep(18)
								print('Transação 40% conlcuída')
								time.sleep(18)
								print('Transação 50% conlcuída')
								time.sleep(18)
								print('Transação 60% conlcuída')
								time.sleep(18)
								print('Transação 70% conlcuída')
								time.sleep(18)
								print('Transação 80% conlcuída')
								time.sleep(18)
								print('Transação 90% conlcuída')
								time.sleep(18)
								print('Transação 99% conlcuída')
								time.sleep(18)
								print('Transação completamente conlcuída')
								print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')

		elif ncarteira == 3:
						print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo3))
						transfer = str(input('Deseja transferir o saldo? '))
						if transfer == 'sim'.upper().lower():
							valor = int(input('Qual valor deseja tranferir? '))
							destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
							taxa = int(0.000041)
							confirmar = str(
								input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
							if confirmar == 'confirmar'.upper().lower():
								if destino == 1:
									saldo1 = saldo1 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R1 é {}'.format(saldo1))
								if destino == 2:
									saldo2 = saldo2 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
								if destino == 3:
									saldo3 = saldo3 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
								if destino == 4:
									saldo4 = saldo4 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R4 é {}'.format(saldo4))
								if destino == 5:
									saldo5 = saldo5 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
								if destino == 6:
									saldo6 = saldo6 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
								else:
									while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
										destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
										if destino == 1:
											saldo1 = saldo1 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R1 é {}'.format(saldo1))
										if destino == 2:
											saldo2 = saldo2 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R2 é {}'.format(saldo2))
										if destino == 3:
											saldo3 = saldo3 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R3 é {}'.format(saldo3))
										if destino == 4:
											saldo4 = saldo4 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R4 é {}'.format(saldo4))
										if destino == 5:
											saldo5 = saldo5 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R5 é {}'.format(saldo5))
										if destino == 6:
											saldo6 = saldo6 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')

		elif ncarteira == 4:
						print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo4))
						transfer = str(input('Deseja transferir o saldo? '))
						if transfer == 'sim'.upper().lower():
							valor = int(input('Qual valor deseja tranferir? '))
							destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
							taxa = int(0.000041)
							confirmar = str(
								input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
							if confirmar == 'confirmar'.upper().lower():
								if destino == 1:
									saldo1 = saldo1 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R1 é {}'.format(saldo1))
								if destino == 2:
									saldo2 = saldo2 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
								if destino == 3:
									saldo3 = saldo3 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
								if destino == 4:
									saldo4 = saldo4 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R4 é {}'.format(saldo4))
								if destino == 5:
									saldo5 = saldo5 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
								if destino == 6:
									saldo6 = saldo6 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
								else:
									while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
										destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
										if destino == 1:
											saldo1 = saldo1 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R1 é {}'.format(saldo1))
										if destino == 2:
											saldo2 = saldo2 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R2 é {}'.format(saldo2))
										if destino == 3:
											saldo3 = saldo3 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R3 é {}'.format(saldo3))
										if destino == 4:
											saldo4 = saldo4 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R4 é {}'.format(saldo4))
										if destino == 5:
											saldo5 = saldo5 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R5 é {}'.format(saldo5))
										if destino == 6:
											saldo6 = saldo6 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')

		elif ncarteira == 5:
						print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo5))
						transfer = str(input('Deseja transferir o saldo? '))
						if transfer == 'sim'.upper().lower():
							valor = int(input('Qual valor deseja tranferir? '))
							destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
							taxa = int(0.000041)
							confirmar = str(
								input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
							if confirmar == 'confirmar'.upper().lower():
								if destino == 1:
									saldo1 = saldo1 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R1 é {}'.format(saldo1))
								if destino == 2:
									saldo2 = saldo2 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
								if destino == 3:
									saldo3 = saldo3 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
								if destino == 4:
									saldo4 = saldo4 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R4 é {}'.format(saldo4))
								if destino == 5:
									saldo5 = saldo5 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
								if destino == 6:
									saldo6 = saldo6 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
								else:
									while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
										destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
										if destino == 1:
											saldo1 = saldo1 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R1 é {}'.format(saldo1))
										if destino == 2:
											saldo2 = saldo2 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R2 é {}'.format(saldo2))
										if destino == 3:
											saldo3 = saldo3 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R3 é {}'.format(saldo3))
										if destino == 4:
											saldo4 = saldo4 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R4 é {}'.format(saldo4))
										if destino == 5:
											saldo5 = saldo5 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R5 é {}'.format(saldo5))
										if destino == 6:
											saldo6 = saldo6 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')

		elif ncarteira == 6:
						print('Criptomoeda: Bitcoin (BTC), Saldo: {}'.format(saldo6))
						transfer = str(input('Deseja transferir o saldo? '))
						if transfer == 'sim'.upper().lower():
							valor = int(input('Qual valor deseja tranferir? '))
							destino = int(input('Qual a carteira de destino? (digitei o número da carteira): '))
							taxa = int(0.000041)
							confirmar = str(
								input("O valor da taxa é {}, digite confirmar, para confirmar a transação".format(taxa)))
							if confirmar == 'confirmar'.upper().lower():
								if destino == 1:
									saldo1 = saldo1 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R1 é {}'.format(saldo1))
								if destino == 2:
									saldo2 = saldo2 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R2 é {}'.format(saldo2))
								if destino == 3:
									saldo3 = saldo3 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R3 é {}'.format(saldo3))
								if destino == 4:
									saldo4 = saldo4 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R4 é {}'.format(saldo4))
								if destino == 5:
									saldo5 = saldo5 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R5 é {}'.format(saldo5))
								if destino == 6:
									saldo6 = saldo6 + valor - taxa
									print('Transação 10% conlcuída')
									time.sleep(18)
									print('Transação 20% conlcuída')
									time.sleep(18)
									print('Transação 30% conlcuída')
									time.sleep(18)
									print('Transação 40% conlcuída')
									time.sleep(18)
									print('Transação 50% conlcuída')
									time.sleep(18)
									print('Transação 60% conlcuída')
									time.sleep(18)
									print('Transação 70% conlcuída')
									time.sleep(18)
									print('Transação 80% conlcuída')
									time.sleep(18)
									print('Transação 90% conlcuída')
									time.sleep(18)
									print('Transação 99% conlcuída')
									time.sleep(18)
									print('Transação completamente conlcuída')
									print('O saldo da carteira R6 é {}'.format(saldo6))
								else:
									while destino != 1 and destino != 2 and destino != 3 and destino != 4 and destino != 5 and destino != 6:
										destino = input('Opção indisponível, por favor digite a opção 1 a 6: ')
										if destino == 1:
											saldo1 = saldo1 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R1 é {}'.format(saldo1))
										if destino == 2:
											saldo2 = saldo2 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R2 é {}'.format(saldo2))
										if destino == 3:
											saldo3 = saldo3 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R3 é {}'.format(saldo3))
										if destino == 4:
											saldo4 = saldo4 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R4 é {}'.format(saldo4))
										if destino == 5:
											saldo5 = saldo5 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R5 é {}'.format(saldo5))
										if destino == 6:
											saldo6 = saldo6 + valor - taxa
											print('Transação 10% conlcuída')
											time.sleep(18)
											print('Transação 20% conlcuída')
											time.sleep(18)
											print('Transação 30% conlcuída')
											time.sleep(18)
											print('Transação 40% conlcuída')
											time.sleep(18)
											print('Transação 50% conlcuída')
											time.sleep(18)
											print('Transação 60% conlcuída')
											time.sleep(18)
											print('Transação 70% conlcuída')
											time.sleep(18)
											print('Transação 80% conlcuída')
											time.sleep(18)
											print('Transação 90% conlcuída')
											time.sleep(18)
											print('Transação 99% conlcuída')
											time.sleep(18)
											print('Transação completamente conlcuída')
											print('O saldo da carteira R6 é {}'.format(saldo6))
							else:
								print('Transação cancelada')
						else:
							print('')


		else:
						while ncarteira != 1 and ncarteira != 2 and ncarteira != 3 and ncarteira != 4 and ncarteira != 5 and ncarteira != 6:
							ncarteira = (input('Carteira não disponível, por favor digite uma carteira de 1 a 6: '))



if opcao != 1 and opcao !=2:
	while opcao != 1 and opcao != 2:
			opcao = int(input('Opção indisponível, por favor digite a opção 1 ou 2: '))